### ISSUE TITLE
Issues with Qwik 0.12

### ISSUE THREAD

**Issue by mahmoudajawad** [robisim74/qwik-speak#13]
Hello.

Looks like adding `qwik-speak` to Qwik app of version 0.12 causes two issues:
- Qwik Optimizer reports errors in `speak-config` where variables `endpoint`, `newSegment` should not be re-defined. I overcame this issue by changing the lines to following:
```ts
// ...
export const loadTranslation$: LoadTranslationFn = $(
  async (lang: string, asset: string, url?: URL) => {
    if (import.meta.env.DEV || asset === "runtime") {
      // Absolute urls on server
      if (isServer && url) {
        const endpoint = `${url.origin}/i18n/${lang}/${asset}.json`;
        const data = await fetch(endpoint);
        return data.json();
      } else {
        const endpoint = `/i18n/${lang}/${asset}.json`;
        const data = await fetch(endpoint);
        return data.json();
      }
    }
  }
);
// ...
export const storeLocale$: StoreLocaleFn = $((locale: SpeakLocale) => {
  // Store locale in cookie
  document.cookie = `locale=${JSON.stringify(locale)};path=/`;

  // Localize the route
  const url = new URL(document.location.href);
  if (url) {
    const pathLang = config.supportedLocales.find((x) =>
      url.pathname.startsWith(`/${x.lang}`)
    )?.lang;

    const regex = new RegExp(`(/${pathLang}/)|(/${pathLang}$)`);
    const segment = url.pathname.match(regex)?.[0];

    if (pathLang && segment) {
      if (locale.lang !== config.defaultLocale.lang) {
        const newSegment = segment.replace(pathLang, locale.lang);
        url.pathname = url.pathname.replace(segment, newSegment);
      } else {
        const newSegment = "/";
        url.pathname = url.pathname.replace(segment, newSegment);
      }
    } else if (locale.lang !== config.defaultLocale.lang) {
      url.pathname = `/${locale.lang}${url.pathname}`;
    }

    window.history.pushState({}, "", url);
  }
});
```
- After previous changes, Qwik build works, but starting compiled site (express) results in all terms being printed as-is without being localised.

**Comment by robisim74** [comment]
Thanks for reporting. I haven't updated to Qwik v0.12 yet because it's really unstable. Anyway I will investigate.

**Comment by robisim74** [comment]
@mahmoudajawad I released a patch (v0.1.4) that should solve the second problem (inlining at compile time).

About the first problem, unfortunately I wasn't able to recreate it (I don't get the same error). There have been a lot of changes in Qwik v0.12 - try verifying all config files & packages versions with a starter app.

**Comment by mahmoudajawad** [comment]
The patch works. The errors though still show up. After looking at the commands run, these errors are reported by eslint _after_ the build is done, meaning there's no harm in them. While I'm still getting them (if I undo the changes and go back to standard config file), the build itself is run perfectly fine.
Thanks.
